/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.naturewise_yearwise_gen;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Anjan
 */
public class FilterForm extends javax.swing.JFrame {

    private NatureWiseYearWiseGenerator NWYWGinstance;
    private String[] caseTypes;
    
    /**
     * Creates new form FilterForm
     * @param instance
     */
    public FilterForm(String[] caseTypes, List<String> permaFilterNature, NatureWiseYearWiseGenerator instance) {
        initComponents();
        this.caseTypes = caseTypes;
        this.listbox_curr_filter.setListData(caseTypes);
        addValuesToList(this.listbox_perma_filter, permaFilterNature);
        NWYWGinstance = instance;
    }
    
    public FilterForm()
    {
       caseTypes = new String[10];
       NWYWGinstance = null;
    }
   
    public Object[] getAllValuesPermanentFilter()
    {
         DefaultListModel model = (DefaultListModel) listbox_perma_filter.getModel();
         return model.toArray();
    }
    
    private DefaultListModel getYearList()
    {
        DefaultListModel model = new DefaultListModel();
        int currYear  = Calendar.getInstance().get(Calendar.YEAR);
        int indx = 0;
        for(int i = currYear; i >= 1965; i--)
        {
            model.addElement(i);
        }
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tabbedPanel_main = new javax.swing.JTabbedPane();
        panel_nature = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listbox_curr_filter = new javax.swing.JList<>();
        panel_year = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listbox_yearFilter = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btn_addToPermanentFilter = new javax.swing.JButton();
        btn_clearSelection_permanentTable = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listbox_perma_filter = new javax.swing.JList<>();
        btn_clearSelection = new javax.swing.JButton();
        btn_caseNaturefilter = new javax.swing.JButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel3.setText("Current Filter for current table");

        listbox_curr_filter.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Filter"));
        listbox_curr_filter.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listbox_curr_filterValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listbox_curr_filter);

        javax.swing.GroupLayout panel_natureLayout = new javax.swing.GroupLayout(panel_nature);
        panel_nature.setLayout(panel_natureLayout);
        panel_natureLayout.setHorizontalGroup(
            panel_natureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_natureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_natureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_natureLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(176, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        panel_natureLayout.setVerticalGroup(
            panel_natureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_natureLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );

        tabbedPanel_main.addTab("Filter By Case Nature", panel_nature);

        listbox_yearFilter.setModel(getYearList());
        jScrollPane3.setViewportView(listbox_yearFilter);

        javax.swing.GroupLayout panel_yearLayout = new javax.swing.GroupLayout(panel_year);
        panel_year.setLayout(panel_yearLayout);
        panel_yearLayout.setHorizontalGroup(
            panel_yearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_yearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_yearLayout.setVerticalGroup(
            panel_yearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_yearLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel_main.addTab("Filter By Year", panel_year);

        jLabel2.setText("Permanent Filter applicable for all tables ");

        btn_addToPermanentFilter.setText("Add selection to Permanent Filter >>");
        btn_addToPermanentFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addToPermanentFilterActionPerformed(evt);
            }
        });

        btn_clearSelection_permanentTable.setText("Clear Selection");
        btn_clearSelection_permanentTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearSelection_permanentTableActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("*Tip: Select one or more Nature using CTRL key");

        listbox_perma_filter.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.pressedBackground"));
        listbox_perma_filter.setBorder(javax.swing.BorderFactory.createTitledBorder("Permanent Filter"));
        listbox_perma_filter.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listbox_perma_filterValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listbox_perma_filter);

        btn_clearSelection.setText("Clear Selection");
        btn_clearSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearSelectionActionPerformed(evt);
            }
        });

        btn_caseNaturefilter.setText("Filter");
        btn_caseNaturefilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_caseNaturefilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tabbedPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_clearSelection)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_caseNaturefilter)))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_clearSelection_permanentTable)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)))
                    .addComponent(btn_addToPermanentFilter))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_clearSelection_permanentTable, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabbedPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clearSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_caseNaturefilter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(btn_addToPermanentFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>                        

    private void listbox_curr_filterValueChanged(javax.swing.event.ListSelectionEvent evt) {                                                 
        // TODO add your handling code here:
         
         
    }                                                

    private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
       
    }                                 

    private void btn_caseNaturefilterActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
         List<String> selectedNatures = this.listbox_curr_filter.getSelectedValuesList();
         this.NWYWGinstance.filterCases( selectedNatures);
    }                                                    

    private void btn_clearSelectionActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        this.listbox_curr_filter.clearSelection();
        btn_caseNaturefilterActionPerformed(null);
    }                                                  

    private void listbox_perma_filterValueChanged(javax.swing.event.ListSelectionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void btn_clearSelection_permanentTableActionPerformed(java.awt.event.ActionEvent evt) {                                                                  
        // TODO add your handling code here:
         int[] indices = this.listbox_perma_filter.getSelectedIndices();
         DefaultListModel model = (DefaultListModel) listbox_perma_filter.getModel();
         for(int i = 0; i < indices.length; i++)
         {
            model.removeElementAt(indices[i]);
         }
         this.NWYWGinstance.permanentFilterValues = new ArrayList(Arrays.asList(model.toArray()));
        
    }                                                                 

    private void btn_addToPermanentFilterActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
         List<String> selectedNatures_currfilter = this.listbox_curr_filter.getSelectedValuesList();
         addValuesToList(this.listbox_perma_filter, selectedNatures_currfilter);
         ArrayList<String> list = new ArrayList<>();
         
         
         for(int i = 0; i < listbox_perma_filter.getModel().getSize(); i++)
         {
             list.add(listbox_perma_filter.getModel().getElementAt(i));
         }
         this.NWYWGinstance.permanentFilterValues = list;
         NWYWGinstance.clearTable();
    }                                                        

    private void addValuesToList(JList<String> listb, List<String> selectedOptions){

        DefaultListModel model = new DefaultListModel<>();
        for(int i = 0; i < selectedOptions.size() ; i++)
        {
            boolean flag = false;
            for(int k = 0; k < listb.getModel().getSize(); k++)
            {
                if(listb.getModel().getElementAt(k).equals(selectedOptions.get(i)))
                {
                    flag = true;
                }
                if(i==0)
                {
                     model.addElement(listb.getModel().getElementAt(k));
                }
            }
            if(!flag)
            {
                model.addElement(selectedOptions.get(i));
            }
        }
        // set the model to permanent filter
        listb.setModel(model);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_addToPermanentFilter;
    private javax.swing.JButton btn_caseNaturefilter;
    private javax.swing.JButton btn_clearSelection;
    private javax.swing.JButton btn_clearSelection_permanentTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JList<String> listbox_curr_filter;
    public javax.swing.JList<String> listbox_perma_filter;
    private javax.swing.JList<String> listbox_yearFilter;
    private javax.swing.JPanel panel_nature;
    private javax.swing.JPanel panel_year;
    private javax.swing.JTabbedPane tabbedPanel_main;
    // End of variables declaration                   
}
