/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.naturewise_yearwise_gen;

import javax.swing.ButtonGroup;

/**
 *
 * @author Anjan
 */
public class SelectAppForm extends javax.swing.JFrame {

    /**
     * Creates new form SelectAppForm
     */
    public SelectAppForm() {
        initComponents();
        addButtonGroup();
        
    }
    
    private void addButtonGroup()
    {
        ButtonGroup bg = new ButtonGroup();
        bg.add(this.checkBox_GNWYW);
        bg.add(this.checkbox_GNWYW_court);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_appSelectHeading = new java.awt.Label();
        panel1 = new java.awt.Panel();
        checkBox_GNWYW = new javax.swing.JCheckBox();
        checkbox_GNWYW_court = new javax.swing.JCheckBox();
        btn_openApp = new javax.swing.JButton();
        lbl_mainHeading = new java.awt.Label();
        lbl_developerInfo = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - Nature Wise Year Wise Generator");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jDesktopPane1.setOpaque(false);

        lbl_appSelectHeading.setAlignment(java.awt.Label.CENTER);
        lbl_appSelectHeading.setBackground(new java.awt.Color(255, 153, 153));
        lbl_appSelectHeading.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        lbl_appSelectHeading.setText("Please Select Your Application");

        panel1.setBackground(new java.awt.Color(153, 204, 255));

        checkBox_GNWYW.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        checkBox_GNWYW.setSelected(true);
        checkBox_GNWYW.setText("Generate Nature Wise and Year Wise Breakup [Single File]");

        checkbox_GNWYW_court.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        checkbox_GNWYW_court.setText("Generate Court-wise, Nature-wise, Year-wise Breakup [Multiple Files and Folders]");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkbox_GNWYW_court)
                    .addComponent(checkBox_GNWYW))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(checkBox_GNWYW, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(checkbox_GNWYW_court, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        btn_openApp.setBackground(new java.awt.Color(255, 153, 153));
        btn_openApp.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_openApp.setText("Open the Application");
        btn_openApp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_openApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openAppActionPerformed(evt);
            }
        });

        lbl_mainHeading.setAlignment(java.awt.Label.CENTER);
        lbl_mainHeading.setBackground(new java.awt.Color(204, 204, 0));
        lbl_mainHeading.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        lbl_mainHeading.setText("Welcome to Nature Wise Year Wise Generator Application");

        lbl_developerInfo.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        lbl_developerInfo.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbl_developerInfo.setText("Designed and Developed By- Anjan Biswas, ICT Technical Manpower (IT Supporting Staff), \nDistrict Court Deoria"); // NOI18N

        jDesktopPane1.setLayer(lbl_appSelectHeading, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(panel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btn_openApp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbl_mainHeading, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbl_developerInfo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_appSelectHeading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_mainHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_developerInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_openApp, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_mainHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_appSelectHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btn_openApp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbl_developerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jDesktopPane1, "card2");

        pack();
    }// </editor-fold>                        

    private void btn_openAppActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if(this.checkBox_GNWYW.isSelected())
        {
            NatureWiseYearWiseGenerator app = new NatureWiseYearWiseGenerator(1);
            app.setFormElementText("Year Wise Nature Wise Generator [Single File]", 
                    "Browse CSV File");
            app.lbl_selectFolder.setVisible(false);
            app.combobox_folder.setVisible(false);
            app.lbl_selctFile.setVisible(false);
            app.combobox_selectFile.setVisible(false);      
            app.tf_output.setVisible(false);
            app.setVisible(true);
            this.setVisible(false);            
        }
        
        else if(this.checkbox_GNWYW_court.isSelected())
        {
            NatureWiseYearWiseGenerator app = new NatureWiseYearWiseGenerator(2);
            app.setFormElementText("Year Wise Nature Wise Generator [CourtWise/Multiple Files and Folders]", 
                    "Browse Folder");
             app.lbl_selectFolder.setVisible(true);
            app.combobox_folder.setVisible(true);
             app.lbl_selctFile.setVisible(true);
            app.combobox_selectFile.setVisible(true);
           
            app.setVisible(true);
            this.setVisible(false);
        }
        
       
        
       
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectAppForm jform = new SelectAppForm();
                jform.setLocationRelativeTo(null);
                jform.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_openApp;
    private javax.swing.JCheckBox checkBox_GNWYW;
    private javax.swing.JCheckBox checkbox_GNWYW_court;
    private javax.swing.JDesktopPane jDesktopPane1;
    private java.awt.Label lbl_appSelectHeading;
    private java.awt.Label lbl_developerInfo;
    private java.awt.Label lbl_mainHeading;
    private java.awt.Panel panel1;
    // End of variables declaration                   
}
